# Generated by Django 3.0.7 on 2020-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('subject', models.CharField(default='', max_length=70)),
                ('msg', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
